---
apiVersion: v1
kind: Service
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloud-controller-manager
  annotations:
    networking.resources.gardener.cloud/from-all-scrape-targets-allowed-ports: '[{"port":10253,"protocol":"TCP"}]'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{  .Values.port }}
    protocol: TCP
  selector:
    app: kubernetes
    role: cloud-controller-manager
