apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
  name: cloud-controller-manager-cloud-provider-equinix-metal
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*cloud-controller-manager*cloud-provider-equinix-metal*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
  name: machine-controller-manager-machine-controller-manager-provider-equinix-metal
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*machine-controller-manager*machine-controller-manager-provider-equinix-metal*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
    fluentbit.gardener.cloud/type: "seed"
  name: machine-controller-manager-equinix-metal-machine-controller-manager
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*machine-controller-manager*equinix-metal-machine-controller-manager*
