apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: equinix-metal
spec:
  type: equinixmetal
  kubernetes:
    versions:
    - version: 1.24.2
    - version: 1.23.7
    - version: 1.22.15
      #expirationDate: "2023-03-15T23:59:59Z"
  machineImages:
  - name: flatcar
    versions:
    - version: 0.0.0-stable
  machineTypes:
  - name: t1.small
    cpu: "4"
    gpu: "0"
    memory: 8Gi
    usable: true
  # volumeTypes is commented out because Equinix Metal retired its volumes storage as a service; it remains here
  # commented because we may be able to pick which drives to use to install
  #volumeTypes:
  #- name: storage_1
  #  class: standard
  #  usable: true
  #- name: storage_2
  #  class: performance
  #  usable: true
  regions: # List of offered metros
  - name: ny
    zones: # List of offered facilities within the respective metro
    - name: ewr1
    - name: ny5
    - name: ny7
  providerConfig:
    apiVersion: equinixmetal.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    machineImages:
    - name: flatcar
      versions:
      - version: 0.0.0-stable
        id: flatcar_stable
    - name: ubuntu
      versions:
      - version: "20.04"
        id: ubuntu_20_04
