---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--packet
  labels:
#    backup.gardener.cloud/provider: packet
#    seed.gardener.cloud/provider: packet
    shoot.gardener.cloud/provider: packet
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--packet
type: Opaque
data:
  apiToken: YXBpVG9rZW4K # apiToken
  projectID: cHJvamVjdElkCg== # projectId
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--packet
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      networking:
        pods: 10.250.0.0/19
      kubernetes:
        version: 1.13.4
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foobar--packet
spec:
  type: packet
  region: ny
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--packet
  providerConfig:
    apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
  infrastructureProviderStatus:
    apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
