image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/provider-equinix-metal
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
maxUnavailable: 1
maxSurge: 50%

resources: {}
vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"

metricsPort: 8080
healthPort: 8081

controllers:
  controlplane:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  heartbeat: 
    renewIntervalSeconds: 30 
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []
ignoreResources: false

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

webhookConfig:
  servicePort: 443
  serverPort: 10250

## settings for metrics, e.g. scraping by seed-prometheus
metrics:
  ## enable metrics scraping
  enableScraping: true

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 25Gi

gardener:
  version: ""
  gardenlet:
    featureGates: {}
  seed:
    provider: equinixmetal
