machineClasses:
- name: class-1
# labels:
#   foo: bar
  projectID: abcd-1234-fff
  OS: alpine_3
  billingCycle: hourly
  metro: ny
  facilities:
  - ewr1
  description: An optional description for machines created by that class.
  machineType: t1.small
  sshKeys:
  - 12345-abcd567-aaf2
  tags:
  - kubernetes.io/cluster/foo
  - kubernetes.io/role/node
  secret:
    cloudConfig: abc
    apiToken: "abd5678"
  credentialsSecretRef:
    name: cloudprovider
    namespace: shoot-namespace
# reservationIDs:
# - res1
# - res2
# reservedDevicesOnly: false
