replicas: 1
kubernetesVersion: 1.7.5
podAnnotations: {}
images:
  cloud-controller-manager: image-repository
port: 443
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi
metro: ny
