---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: kube-system
  annotations:
    # The MetalLB config is managed by the Equinix Metal CCM, however an empty ConfigMap must be
    # pre-created. The following annotation tells Gardener to ignore changes to the ConfigMap after
    # the initial creation so that Gardener doesn't override the config set by the CCM.
    resources.gardener.cloud/ignore: "true"
data:
  config: |
    peers: []
    address-pools: []
