name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path: .github/actions/prepare-release
    permissions:
      contents: read
      pull-requests: write

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    secrets: inherit  
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    with:
      name: gardener-extension-provider-equinix-metal
      version: ${{ needs.prepare.outputs.version }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: extensions/provider-equinix-metal
      oci-platforms: linux/amd64
      target: gardener-extension-provider-equinix-metal

  helmcharts:
    name: Build Helmcharts
    needs:
      - prepare
      - oci-images
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: provider-equinix-metal
            dir: charts/gardener-extension-provider-equinix-metal
            mappings:
              - ref: ocm-resource:gardener-extension-provider-equinix-metal.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-provider-equinix-metal.tag
                attribute: image.tag
    with:
      name: ${{ matrix.args.name }}
      dir: ${{ matrix.args.dir }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: charts/gardener/extensions
      ocm-mappings: ${{ toJSON(matrix.args.mappings) }}

  verify:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: run-verify
        run: |
          .ci/verify
